services:
  - type: web
    name: yamaha-matakos-backend
    env: node
    root: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        value: http://207.154.226.88
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        value: noreply@yamaha-matakos.gr
      - key: BREVO_TO_EMAIL
        value: info@yamaha-matakos.gr
      - key: BREVO_SENDER_NAME
        value: Yamaha Matakos Contact
      - key: EMAIL_USER
        value: sotdaskalou@gmail.com
